import { readFileSync, writeFileSync, readdirSync, statSync } from 'fs';
import { join, relative, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const AGENT_DIR = join(__dirname, '..', 'agent');
const OUTPUT_FILE = join(__dirname, '..', 'src', 'agent-bundle.ts');

interface BundledFile {
  path: string;
  content: string;
}

function collectFiles(dir: string, base: string): BundledFile[] {
  const files: BundledFile[] = [];

  for (const entry of readdirSync(dir)) {
    const fullPath = join(dir, entry);
    const stat = statSync(fullPath);

    if (stat.isDirectory()) {
      files.push(...collectFiles(fullPath, base));
    } else {
      const relativePath = relative(base, fullPath);
      const content = readFileSync(fullPath, 'utf-8');
      files.push({ path: relativePath, content });
    }
  }

  return files;
}

const files = collectFiles(AGENT_DIR, AGENT_DIR);

const output = `// Auto-generated by scripts/bundle-agent.ts — do not edit manually
export const AGENT_FILES: Array<{ path: string; content: string }> = ${JSON.stringify(files, null, 2)};
`;

writeFileSync(OUTPUT_FILE, output);
console.log(`Bundled ${files.length} agent files into ${OUTPUT_FILE}`);
